/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Data.MateriaData;
import Data.MiConexion;
import Entidades.Materia;
import java.sql.Connection;

/**
 *
 * @author Pat
 */
public class Fri_Materias extends javax.swing.JInternalFrame {

   private MiConexion con = null;
    private MateriaData matDa;

    public Fri_Materias() {
        initComponents();
        this.con = new MiConexion("jdbc:mysql://localhost/tp_universidad", "root", "");
        this.matDa = new MateriaData (con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lbl_idMateria = new javax.swing.JLabel();
        lblNombreMateria = new javax.swing.JLabel();
        lbl_anio = new javax.swing.JLabel();
        txt_idMateria = new javax.swing.JTextField();
        txtNombreMateria = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        chkEstado = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        btGuarda = new javax.swing.JButton();
        btBorra = new javax.swing.JButton();
        btActualiza = new javax.swing.JButton();
        btLimpia = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitulo.setText("MATERIA");

        lbl_idMateria.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_idMateria.setText("Codigo:");

        lblNombreMateria.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNombreMateria.setText("Materia:");

        lbl_anio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_anio.setText("Año:");

        txt_idMateria.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtNombreMateria.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtAnio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btBuscar.setText("buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        chkEstado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chkEstado.setText("Estado Activo");

        btGuarda.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btGuarda.setText("Guardar");
        btGuarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardaActionPerformed(evt);
            }
        });

        btBorra.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btBorra.setText("Borra");
        btBorra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorraActionPerformed(evt);
            }
        });

        btActualiza.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btActualiza.setText("Actualizar");
        btActualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizaActionPerformed(evt);
            }
        });

        btLimpia.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btLimpia.setText("Limpia");
        btLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(chkEstado))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btGuarda)
                                .addGap(33, 33, 33)
                                .addComponent(btBorra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btActualiza)
                                .addGap(26, 26, 26)
                                .addComponent(btLimpia))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblNombreMateria)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_idMateria)
                                        .addGap(30, 30, 30)
                                        .addComponent(txt_idMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbl_anio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(57, 57, 57)
                                .addComponent(btBuscar)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblTitulo)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txt_idMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_idMateria)
                    .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreMateria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_anio))
                .addGap(67, 67, 67)
                .addComponent(chkEstado)
                .addGap(32, 32, 32)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btGuarda)
                    .addComponent(btBorra)
                    .addComponent(btActualiza)
                    .addComponent(btLimpia))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardaActionPerformed
       Materia m=new Materia();
       String nombre= txtNombreMateria.getText();
       int anio=Integer.parseInt(txtAnio.getText());
       boolean estado=chkEstado.isSelected();
       m.setNombre(nombre);
       m.setAnio(anio);
       m.setActivo(estado);
       matDa.guardarMateria(m);
      
       
    }//GEN-LAST:event_btGuardaActionPerformed

    private void btBorraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorraActionPerformed
     //Materia m=new Materia();
       int idMat= Integer.parseInt(txt_idMateria.getText());
        matDa.borrarMateria(idMat);
        //matDa.borrarMateria(Integer.parseInt(txtAnio.getText()));
    }//GEN-LAST:event_btBorraActionPerformed

    private void btActualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizaActionPerformed
       Materia ma=new Materia();
       String nombre= txtNombreMateria.getText();
       int anio=Integer.parseInt(txtAnio.getText());
       boolean estado=chkEstado.isSelected();
       int idMat= Integer.parseInt(txt_idMateria.getText());
       ma.setIdMateria(idMat);
       ma.setNombre(nombre);
       ma.setAnio(anio);
       ma.setActivo(estado);
      
       
        matDa.actualizarMateria(ma);
    }//GEN-LAST:event_btActualizaActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
     
        int idMat= Integer.parseInt(txt_idMateria.getText());
           Materia mat=matDa.buscarMateria(idMat);
            txtNombreMateria.setText(mat.getNombre());
            String anio=String.valueOf(mat.getAnio());
            txtAnio.setText(anio);
            chkEstado.setSelected(mat.isActivo());
            
           
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiaActionPerformed
        txt_idMateria.setText("");txtNombreMateria.setText("");txtAnio.setText("");
        chkEstado.setSelected(false);

    }//GEN-LAST:event_btLimpiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualiza;
    private javax.swing.JButton btBorra;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btGuarda;
    private javax.swing.JButton btLimpia;
    private javax.swing.JCheckBox chkEstado;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblNombreMateria;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lbl_anio;
    private javax.swing.JLabel lbl_idMateria;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtNombreMateria;
    private javax.swing.JTextField txt_idMateria;
    // End of variables declaration//GEN-END:variables
}
