package Vistas;

import Entidades.Alumno;
import Entidades.Materia;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Data.AlumnoData;
import Data.CursadaData;
import Data.MateriaData;
import Data.MiConexion;

/**
 *
 * @author Grupo 10
 */
public class Fri_ListarAlumnos extends javax.swing.JInternalFrame {

    private MiConexion con = null;
    private AlumnoData alDa;
    private MateriaData maDa;
    private CursadaData cuDa;
    private DefaultTableModel modelo;
    public Fri_ListarAlumnos() {
        initComponents();
        this.con = new MiConexion("jdbc:mysql://localhost/tp_universidad", "root", "");
        this.alDa = new AlumnoData (con);
        this.maDa = new MateriaData (con);
        this.cuDa = new CursadaData (con,alDa,maDa);
        this.modelo=new DefaultTableModel();
        llenarCombos();
       // llenarTablas();
        armarCabecera();
        //llenarTablas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lbl_infoMateria = new javax.swing.JLabel();
        cbxAlumno = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaAlumnos = new javax.swing.JTable();
        bListar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo.setText("LISTAR ALUMNOS POR MATERIA");

        lbl_infoMateria.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_infoMateria.setText("MATERIA");

        cbxAlumno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jTablaAlumnos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "NOTA"
            }
        ));
        jScrollPane1.setViewportView(jTablaAlumnos);

        bListar.setText("listar alumnos");
        bListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListarActionPerformed(evt);
            }
        });

        jButton1.setText("salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lbl_infoMateria)
                        .addGap(46, 46, 46)
                        .addComponent(cbxAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(333, Short.MAX_VALUE)
                        .addComponent(lblTitulo)))
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(bListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitulo)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_infoMateria)
                    .addComponent(cbxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bListar)
                    .addComponent(jButton1))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListarActionPerformed
        llenarTablas();
    }//GEN-LAST:event_bListarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
  public void llenarCombos(){
    for (Materia ma:maDa.listarMateria()) {
        cbxAlumno.addItem(ma);
        
    }}
  public void armarCabecera(){
ArrayList<Object>col=new ArrayList();
col.add("id");
col.add("nombre");
col.add("apellido");

    for (Object colu : col) {
        modelo.addColumn(colu);
        
    }
    jTablaAlumnos.setModel(modelo);

}
      public void llenarTablas(){
        borrarFilas();
        //int mas=jTablaAlumnos.getSelectedRow();
    Materia ma=(Materia)cbxAlumno.getSelectedItem();
    
        System.out.println(ma);
        //Materia ma=new Materia();
        //cuDa.inscripcionMateria(al);

        if(ma!=null){
        // Alumno alu=alDa.buscarAlumno(al.getIdAlumno());
        for (Alumno c:cuDa.inscripcionAlumno(ma)) {
             //if(jTablaAlumnos.getValueAt(mas,1).equals(c.getNombre())){
             System.out.println(c.getNombre());         
            modelo.addRow(new Object[]{c.getIdAlumno(),c.getNombre(),c.getApellido()});
             }
             //}
            }
          
        }
        public void borrarFilas(){
    
        int a=modelo.getRowCount()-1;//cuenta las filas pero el indice es uno menos
        for (int i = a; i >=0; i--) {
            modelo.removeRow(i);
        }}

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bListar;
    private javax.swing.JComboBox<Materia> cbxAlumno;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaAlumnos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lbl_infoMateria;
    // End of variables declaration//GEN-END:variables
}
