package Vistas;

import Entidades.Alumno;
import Entidades.Cursada;
import Entidades.Materia;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Data.AlumnoData;
import Data.CursadaData;
import Data.MateriaData;
import Data.MiConexion;

/**
 *
 * @author Grupo 10
 */
public class Fri_Inscripciones extends javax.swing.JInternalFrame {

   private MiConexion con = null;
    private AlumnoData alDa;
    private MateriaData maDa;
    private CursadaData cuDa;
    private DefaultTableModel modelo;
    public Fri_Inscripciones() {
        initComponents();
        this.con = new MiConexion("jdbc:mysql://localhost/tp_universidad", "root", "");
        this.alDa = new AlumnoData (con);
        this.maDa = new MateriaData (con);
        this.cuDa = new CursadaData (con,alDa,maDa);
        this.modelo=new DefaultTableModel();
        llenarCombos();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lbl_infoAlumno = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        btInscribe = new javax.swing.JButton();
        btAnulaInsc = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        cbxAlumno = new javax.swing.JComboBox<>();
        botonInscriptas = new javax.swing.JRadioButton();
        noIinscriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaMaterias = new javax.swing.JTable();

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitulo.setText("Inscripcion a Cursada");

        lbl_infoAlumno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_infoAlumno.setText("ALUMNO");

        lblSubtitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSubtitulo.setText("LISTADO DE MATERIAS");

        btInscribe.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btInscribe.setText("Inscribir");
        btInscribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInscribeActionPerformed(evt);
            }
        });

        btAnulaInsc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btAnulaInsc.setText("Anular Inscripcion");
        btAnulaInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnulaInscActionPerformed(evt);
            }
        });

        btSalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        cbxAlumno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cbxAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAlumnoActionPerformed(evt);
            }
        });

        botonInscriptas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonInscriptas.setText("Inscriptas");
        botonInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInscriptasActionPerformed(evt);
            }
        });

        noIinscriptas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        noIinscriptas.setText("No Inscriptas");
        noIinscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noIinscriptasActionPerformed(evt);
            }
        });

        jTablaMaterias.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "AÑO"
            }
        ));
        jScrollPane1.setViewportView(jTablaMaterias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btAnulaInsc))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btInscribe)
                        .addGap(287, 287, 287)
                        .addComponent(btSalir)))
                .addContainerGap(466, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_infoAlumno)
                        .addGap(18, 18, 18)
                        .addComponent(cbxAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(lblSubtitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(botonInscriptas)
                        .addGap(129, 129, 129)
                        .addComponent(noIinscriptas)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitulo)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_infoAlumno)
                    .addComponent(cbxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(lblSubtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noIinscriptas)
                    .addComponent(botonInscriptas))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btInscribe)
                    .addComponent(btAnulaInsc)
                    .addComponent(btSalir))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAlumnoActionPerformed
   //llenarTablas();
    }//GEN-LAST:event_cbxAlumnoActionPerformed

    private void botonInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInscriptasActionPerformed
noIinscriptas.setSelected(false);
        llenarTablas();
    }//GEN-LAST:event_botonInscriptasActionPerformed

    private void noIinscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noIinscriptasActionPerformed
 botonInscriptas.setSelected(false);
        llenarTablas1();       // TODO add your handling code here:
    }//GEN-LAST:event_noIinscriptasActionPerformed

    private void btInscribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInscribeActionPerformed
      Alumno al=(Alumno)cbxAlumno.getSelectedItem();
      int ta=jTablaMaterias.getSelectedRow();
      Materia ma=new Materia();
      Cursada ca=new Cursada();
        
       if(al!=null && ta!=-1){
           
            ma.setIdMateria((Integer)jTablaMaterias.getValueAt(ta,0));
            ma.setNombre((String)jTablaMaterias.getValueAt(ta,1));
            ma.setAnio((Integer)jTablaMaterias.getValueAt(ta,2));
            ma.setActivo(true);
            
             ca.setAl(al);
            ca.setMa(ma);
            ca.setNota(0);
            cuDa.guardarCursada(ca);
                    // Alumno alu=alDa.buscarAlumno(al.getIdAlumno());
        //for (Cursada c:cuDa.guardarCursada(ca)) {
             //System.out.println(c.getNombre());         
            //modelo.addRow(new Object[]{c.getIdMateria(),c.getNombre(),c.getAnio()});
           // }
       
       }
    }//GEN-LAST:event_btInscribeActionPerformed

    private void btAnulaInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnulaInscActionPerformed
       Alumno al=(Alumno)cbxAlumno.getSelectedItem();
      int ta=jTablaMaterias.getSelectedRow();
      Materia ma=new Materia();
      Cursada ca=new Cursada();
        
       if(al!=null && ta!=-1){
           
            ma.setIdMateria((Integer)jTablaMaterias.getValueAt(ta,0));
            ca=cuDa.obtenerCursada(al.getIdAlumno(),ma.getIdMateria());
            cuDa.borrarCursada(ca.getIdCursada());
            }
    }//GEN-LAST:event_btAnulaInscActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
       this.dispose(); 
    }//GEN-LAST:event_btSalirActionPerformed
 public void activarCampos(){
     
 }
 public void DesactivarCampos(){
 }
    
    public void llenarCombos(){
    for (Alumno al:alDa.listarAlumnos()) {
        cbxAlumno.addItem(al);
        
    }}
public void armarCabecera(){
ArrayList<Object>col=new ArrayList();
col.add("ad materia");
col.add("nombre");
col.add("anio");
    for (Object colu : col) {
        modelo.addColumn(colu);
        
    }
    jTablaMaterias.setModel(modelo);

}
    public void llenarTablas(){
        borrarFilas();
    Alumno al=(Alumno)cbxAlumno.getSelectedItem();
        System.out.println(al);
        //Materia ma=new Materia();
        //cuDa.inscripcionMateria(al);

        if(al!=null){
        // Alumno alu=alDa.buscarAlumno(al.getIdAlumno());
        for (Materia c:cuDa.inscripcionMateria(al)) {
             System.out.println(c.getNombre());         
            modelo.addRow(new Object[]{c.getIdMateria(),c.getNombre(),c.getAnio()});
            }
          
        }

    }
        public void llenarTablas1(){
        borrarFilas();
    Alumno al=(Alumno)cbxAlumno.getSelectedItem();
        System.out.println(al);
        //Materia ma=new Materia();
        //cuDa.inscripcionMateria(al);

        if(al!=null){
        // Alumno alu=alDa.buscarAlumno(al.getIdAlumno());
        for (Materia c:cuDa.noInscripcionMateria(al)) {
             System.out.println(c.getNombre());         
            modelo.addRow(new Object[]{c.getIdMateria(),c.getNombre(),c.getAnio()});
            }
          
        }

    }
    public void borrarFilas(){
    
        int a=modelo.getRowCount()-1;//cuenta las filas pero el indice es uno menos
        for (int i = a; i >=0; i--) {
            modelo.removeRow(i);
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonInscriptas;
    private javax.swing.JButton btAnulaInsc;
    private javax.swing.JButton btInscribe;
    private javax.swing.JButton btSalir;
    private javax.swing.JComboBox<Alumno> cbxAlumno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaMaterias;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lbl_infoAlumno;
    private javax.swing.JRadioButton noIinscriptas;
    // End of variables declaration//GEN-END:variables
}
