package Vistas;

import Entidades.Alumno;
import Entidades.Cursada;
import Entidades.Materia;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Data.AlumnoData;
import Data.CursadaData;
import Data.MateriaData;
import Data.MiConexion;

/**
 *
 * @author Grupo 10
 */
public class Fri_Notas extends javax.swing.JInternalFrame {
   private MiConexion con = null;
    private AlumnoData alDa;
    private MateriaData maDa;
    private CursadaData cuDa;
    private DefaultTableModel modelo;
    public Fri_Notas() {
        initComponents();
         this.con = new MiConexion("jdbc:mysql://localhost/tp_universidad", "root", "");
        this.alDa = new AlumnoData (con);
        this.maDa = new MateriaData (con);
        this.cuDa = new CursadaData (con,alDa,maDa);
        this.modelo=new DefaultTableModel();
        llenarCombos();
        armarCabecera();
        pedirDatos(); 
          
        
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lbl_infoAlumno = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        btGuarda = new javax.swing.JButton();
        cbxAlumno = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaNotas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitulo.setText("Actualizacion de Notas");

        lbl_infoAlumno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_infoAlumno.setText("ALUMNO");

        lblSubtitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSubtitulo.setText("Listado y Carga de Notas");

        btGuarda.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btGuarda.setText("actualizar nota");
        btGuarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardaActionPerformed(evt);
            }
        });

        cbxAlumno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cbxAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAlumnoActionPerformed(evt);
            }
        });

        jTablaNotas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTablaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "MATERIA", "NOTA"
            }
        ));
        jScrollPane1.setViewportView(jTablaNotas);

        jButton1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton1.setText("salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_infoAlumno)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSubtitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 523, Short.MAX_VALUE))
                            .addComponent(cbxAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 339, Short.MAX_VALUE)
                        .addComponent(btGuarda)
                        .addGap(368, 368, 368)))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitulo)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_infoAlumno)
                    .addComponent(cbxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblSubtitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btGuarda)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAlumnoActionPerformed
        llenarTablas();
        //pedirDatos(); 
        //String nota=JOptionPane.showInputDialog("ingrese la nota");

    }//GEN-LAST:event_cbxAlumnoActionPerformed

    private void btGuardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardaActionPerformed
       pedirDatos();
        int ta=jTablaNotas.getSelectedRow();
      Alumno al=(Alumno)cbxAlumno.getSelectedItem();
        System.out.println(al);
        //Materia ma=new Materia();
        //cuDa.inscripcionMateria(al);    
        if(al!=null){
           
            // Alumno alu=alDa.buscarAlumno(al.getIdAlumno());
        for (Materia c:cuDa.inscripcionMateria(al)) {
            if(jTablaNotas.getValueAt(ta,1).equals(c.getNombre())){
             Cursada cu=cuDa.obtenerCursada(al.getIdAlumno(),c.getIdMateria());
             //System.out.println(c.getNombre()); 
            // System.out.println(jTablaNotas.getValueAt(ta, 2));
             double nro= Double.parseDouble((String) jTablaNotas.getValueAt(ta, 2));
            
             //modelo.addRow(new Object[]{cu.getIdCursada(),c.getNombre(),nro});
            
           // System.out.println(al.getIdAlumno()+ c.getIdMateria() + nro);
            cuDa.actualizarNota(al.getIdAlumno(),c.getIdMateria(),nro);}
            
            }
       
        }
        
           


    }//GEN-LAST:event_btGuardaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void llenarCombos(){
    for (Alumno al:alDa.listarAlumnos()) {
       cbxAlumno.addItem(al);
        
    }}
    
    public void armarCabecera(){
ArrayList<Object>col=new ArrayList();
col.add("Id");
col.add("Materia");
col.add("Nota");
    for (Object colu : col) {
        modelo.addColumn(colu);
        
    }
    jTablaNotas.setModel(modelo);

}
        public void llenarTablas(){
       borrarFilas();
    Alumno al=(Alumno)cbxAlumno.getSelectedItem();
        //System.out.println(al);
        //Materia ma=new Materia();
        //cuDa.inscripcionMateria(al);    
        if(al!=null){
            // Alumno alu=alDa.buscarAlumno(al.getIdAlumno());
        for (Materia c:cuDa.inscripcionMateria(al)) {
             Cursada cu=cuDa.obtenerCursada(al.getIdAlumno(),c.getIdMateria());
             System.out.println(c.getNombre());         
            modelo.addRow(new Object[]{cu.getIdCursada(),c.getNombre(),cu.getNota()});
            }
          
        }}
         public void pedirDatos(){
                
             System.out.println(jTablaNotas.getSelectedRow());
           
       if(jTablaNotas.getSelectedRow()!=-1){
           String nota=JOptionPane.showInputDialog("ingrese la nota");
           jTablaNotas.setValueAt(nota,jTablaNotas.getSelectedRow(), 2);
            System.out.println("  "+ jTablaNotas.getSelectedRow());
           
       }
            
           
         }
        
          public void borrarFilas(){
    
        int a=modelo.getRowCount()-1;//cuenta las filas pero el indice es uno menos
        for (int i = a; i >=0; i--) {
            modelo.removeRow(i);
        }}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuarda;
    private javax.swing.JComboBox<Alumno> cbxAlumno;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaNotas;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lbl_infoAlumno;
    // End of variables declaration//GEN-END:variables
}
