package Vistas;

import Data.MiConexion;
import Entidades.Alumno;
import java.sql.Date;
import java.time.LocalDate;
import java.time.Month;
import java.util.Calendar;
import Data.AlumnoData;
import Data.MateriaData;
import java.time.ZoneId;
import javax.swing.JOptionPane;


/**
 *
 * @author Grupo10
 */
public class Fri_Alumnos extends javax.swing.JInternalFrame {

  private MiConexion con = null;
    private AlumnoData alDa;
    public Fri_Alumnos() {
        initComponents();
        this.con = new MiConexion("jdbc:mysql://localhost/tp_universidad", "root", "");
        this.alDa = new AlumnoData (con);
        btGuarda.setEnabled(false);
        btBorra.setEnabled(false);
        btActualiza.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lbl_idAlumno = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txt_idAlumno = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        chkEstado = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        btGuarda = new javax.swing.JButton();
        btBorra = new javax.swing.JButton();
        btActualiza = new javax.swing.JButton();
        btLimpia = new javax.swing.JButton();
        lblDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        fecnac = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btCerrar = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitulo.setText("ALUMNO");

        lbl_idAlumno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_idAlumno.setText("Legajo:");

        lblApellido.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblApellido.setText("Apellido:");

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNombre.setText("Nombre:");

        txt_idAlumno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_idAlumno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_idAlumnoFocusLost(evt);
            }
        });

        txtApellido.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoFocusLost(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });

        btBuscar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btBuscar.setText("BUSCAR");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        chkEstado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chkEstado.setText("Estado Activo");

        btGuarda.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btGuarda.setText("Guardar");
        btGuarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardaActionPerformed(evt);
            }
        });

        btBorra.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btBorra.setText("Borra");
        btBorra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorraActionPerformed(evt);
            }
        });

        btActualiza.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btActualiza.setText("Actualizar");
        btActualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizaActionPerformed(evt);
            }
        });

        btLimpia.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btLimpia.setText("Limpia");
        btLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiaActionPerformed(evt);
            }
        });

        lblDni.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDni.setText("dni:");

        txtDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDniFocusLost(evt);
            }
        });
        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("fecha :");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btCerrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btCerrar.setText("cerrar");
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(chkEstado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblApellido)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblDni)
                                        .addComponent(lblNombre)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_idAlumno, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDni, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fecnac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_idAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btGuarda)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btBorra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                        .addComponent(btActualiza)
                                        .addGap(26, 26, 26)
                                        .addComponent(btLimpia)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btCerrar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(55, 55, 55))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(234, 234, 234))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_idAlumno)
                            .addComponent(txt_idAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellido)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(fecnac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(chkEstado)
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btGuarda)
                    .addComponent(btBorra)
                    .addComponent(btActualiza)
                    .addComponent(btLimpia))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardaActionPerformed
       if(txtApellido.getText().length()!= 0 && txtNombre.getText().length()!= 0 && txtDni.getText().length()!= 0 && fecnac.getDate()!= null){
        
        Alumno al=new Alumno();
       String nombre= txtNombre.getText();
       String apellido= txtApellido.getText();
//       int anio=fecnac.getCalendar().get(Calendar.YEAR);
//       int mes=fecnac.getCalendar().get(Calendar.MONTH)+1;
//       int dia=fecnac.getCalendar().get(Calendar.DAY_OF_MONTH);
       //String fecNac=""+anio+"-"+mes+"-"+dia;
       java.util.Date sfecha =fecnac.getDate();
       LocalDate fechaNac = sfecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
       int dni=Integer.parseInt(txtDni.getText());
       boolean estado=chkEstado.isSelected();
       al.setNombre(nombre);
       al.setApellido(apellido);
       al.setFechaNac(fechaNac);
       al.setDni(dni);
       al.setActivo(estado);
       alDa.guardarAlumno(al);
       txt_idAlumno.setText(al.getIdAlumno()+"");
       btGuarda.setEnabled(false);}else{
        JOptionPane.showMessageDialog(this,"faltan rellenar campos para guardar");
       }
    }//GEN-LAST:event_btGuardaActionPerformed

    private void btBorraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorraActionPerformed
       int idAl= Integer.parseInt(txt_idAlumno.getText());
         alDa.borrarAlumno(idAl);
         btBorra.setEnabled(false);
    }//GEN-LAST:event_btBorraActionPerformed

    private void btActualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizaActionPerformed
       Alumno al=new Alumno();
       String nombre= txtNombre.getText();
       String apellido= txtApellido.getText();
       int anio=fecnac.getCalendar().get(Calendar.YEAR);
       int mes=fecnac.getCalendar().get(Calendar.MONTH)+1;
       int dia=fecnac.getCalendar().get(Calendar.DAY_OF_MONTH);
       //String fecNac=""+anio+"-"+mes+"-"+dia;
       int dni=Integer.parseInt(txtDni.getText());
       boolean estado=chkEstado.isSelected();
       int idAl=Integer.parseInt(txt_idAlumno.getText());
       al.setNombre(nombre);
       al.setApellido(apellido);
       al.setFechaNac(LocalDate.of(anio,mes,dia));
       al.setDni(dni);
       al.setActivo(estado);
       al.setIdAlumno(idAl);
      
       alDa.actualizarAlumno(al);
   
    }//GEN-LAST:event_btActualizaActionPerformed

    private void btLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiaActionPerformed
         txtNombre.setText("");
            txtApellido.setText("");
        fecnac.setToolTipText("");
            txtDni.setText("");
            chkEstado.setSelected(false);
             txt_idAlumno.setText("");     
            fecnac.setDate(null);
            btActualiza.setEnabled(false);
            btBorra.setEnabled(false);
            btGuarda.setEnabled(false);
    }//GEN-LAST:event_btLimpiaActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
         btBorra.setEnabled(true);
        btActualiza.setEnabled(true);
        String val= "[0-9]*";//exp regular
        if(txt_idAlumno.getText().matches(val)&& txt_idAlumno.getText().length() != 0){
        
        int idAl= Integer.parseInt(txt_idAlumno.getText());
         
           Alumno al=alDa.buscarAlumno(idAl);
            txtNombre.setText(al.getNombre());
            txtApellido.setText(al.getApellido());
           String dni=String.valueOf(al.getDni());
            txtDni.setText(dni);
            chkEstado.setSelected(al.isActivo());
//             int anio=al.getFechaNac().getYear();
//             int mes=al.getFechaNac().getMonthValue();
//       int dia=al.getFechaNac().getDayOfMonth();
//       String fecNac=""+anio+"-"+mes+"-"+dia;
            
           
            LocalDate lc = al.getFechaNac();
            java.util.Date date = Date.from(lc.atStartOfDay(ZoneId.systemDefault()).toInstant());
            fecnac.setDate(date);}else{
         JOptionPane.showMessageDialog(this,"debe ingresar al menos un numero para buscar");
        }
           
    }//GEN-LAST:event_btBuscarActionPerformed

    private void txt_idAlumnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_idAlumnoFocusLost
      String val= "[0-9]*";//exp regular
        if(!txt_idAlumno.getText().matches(val) || txt_idAlumno.getText().length() == 0){
            JOptionPane.showMessageDialog(this,"Ingrese un NUMERO\n-No deje el campo vacío-");
//            txt_idAlumno.requestFocus();
        }
    }//GEN-LAST:event_txt_idAlumnoFocusLost

    private void txtApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoFocusLost
           if(txtApellido.getText().length()== 0){
          JOptionPane.showMessageDialog(this,"debe llenar el campo");
       txtApellido.requestFocus();
        
        }
    }//GEN-LAST:event_txtApellidoFocusLost

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
             if(txtNombre.getText().length()== 0){
          JOptionPane.showMessageDialog(this,"debe llenar el campo");
       txtNombre.requestFocus();
        
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtDniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDniFocusLost
                    String val= "[0-9]*";//exp regularesif(
       if(!txtDni.getText().matches(val)){
       JOptionPane.showMessageDialog(this,"no ingreso un numero");
       txtDni.requestFocus();}
    }//GEN-LAST:event_txtDniFocusLost

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        btGuarda.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualiza;
    private javax.swing.JButton btBorra;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCerrar;
    private javax.swing.JButton btGuarda;
    private javax.swing.JButton btLimpia;
    private javax.swing.JCheckBox chkEstado;
    private com.toedter.calendar.JDateChooser fecnac;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lbl_idAlumno;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txt_idAlumno;
    // End of variables declaration//GEN-END:variables
}
